### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by balzybob69** [Damitrix/AfestaExtract#1]
Anyway we can get a readme for this? It's not clear how to use it.

**Comment by Damitrix** [comment]
I'm sorry, i wrote this years ago, and afesta probably changed their API anyways. If you were logged into LPEG on your local PC, this was a way to download and extract haptics script files for Afesta Videos. All of the code is in the MainWindow.xaml.cs file, if you'd like to take a look.

**Comment by balzybob69** [comment]
Thanks for the quick response! I wasn't expecting anything back but glad you saw it. Agreed the api probably changed but I'll poke around in the code and see if I can figure something out.

**Comment by balzybob69** [comment]
I poked through the code a bit and was able to figure out the right things to Google. I didn't write a program but I figured out a working method. I wrote a guide for it as a couple people were asking on reddit as well. 

https://drive.google.com/drive/folders/1qZ9nb9cUW2dHcHQLX6fOoJJDV8JzNh8X?usp=drive_link
